# -*- coding: utf-8 -*-
"""CustomerSegmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lhJqBVgEJNNkeP9541i0jq0D1jcqutB_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import homogeneity_score, completeness_score, v_measure_score, silhouette_score
from sklearn import metrics

df = pd.read_csv("/content/Mall_Customers.csv")
df.head()

df.shape

"""Data Pre-processing"""

df.isnull().sum()

X = df.iloc[:,[3,4]].values

scaler = StandardScaler()
X = scaler.fit_transform(X)

eps_values = [0.1, 0.2, 0.3, 0.4, 0.5]
min_samples_values = [2, 3, 4, 5, 6, 7, 8, 9, 10]

"""Finding best parameter values"""

best_score = -1
best_eps = None
best_min_samples = None

for eps in eps_values:
    for min_samples in min_samples_values:
        dbscan = DBSCAN(eps=eps, min_samples=min_samples)
        dbscan.fit(X)
        labels = dbscan.labels_
        if len(set(labels)) > 1:
            score = silhouette_score(X, labels)

            if score > best_score:
                best_score = score
                best_eps = eps
                best_min_samples = min_samples

print(f"Best score: {best_score}")
print(f"Best eps: {best_eps}")
print(f"Best min_samples: {best_min_samples}")

"""1- Apply the DBSCAN method"""

model1 = DBSCAN(eps=0.4,min_samples=8)
clusters = model1.fit_predict(X)

# Display cluster properties
n_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)
n_noise = list(clusters).count(-1)
print('Number of clusters:', n_clusters)
print('Number of noise points:', n_noise)

for i in range(n_clusters):
    print('Cluster', i+1, ':')
    cluster_size = len(X[clusters == i])
    print('Number of observations:', cluster_size)
    cluster_homogeneity = np.sum(clusters == i) / cluster_size
    print('Homogeneity:', cluster_homogeneity)
    cluster_heterogeneity = np.sum(clusters != i) / (len(X) - cluster_size)
    print('Heterogeneity:', cluster_heterogeneity)
    print('------------------------')

"""Visualize the clusters"""

# Visualize the clusters
plt.scatter(X[clusters == -1, 0], X[clusters == -1, 1], s=100, c='black', label='Noise')
for i in range(n_clusters):
    plt.scatter(X[clusters == i, 0], X[clusters == i, 1], s=100, label=f'Cluster {i+1}')
plt.title('DBSCAN Clustering with distance metric euclidean')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

"""Cluster Green - Balanced Customers :

They earn less and spend less. We can see people have low annual income and low spending scores, this is quite reasonable as people having low salaries prefer to buy less, in fact, these are the wise people who know how to spend and save money. The shops/mall will be least interested in people belonging to this cluster.


Cluster Yellow - Pinch Penny Customers :
Earning high and spending less. We see that people have high income but low spending scores, this is interesting. Maybe these are the people who are unsatisfied or unhappy by the mall’s services. These can be the prime targets of the mall, as they have the potential to spend money. So, the mall authorities will try to add new facilities so that they can attract these people and can meet their needs.

Cluster Red - Normal Customer :
Customers are average in terms of earning and spending An Average consumer in terms of spending and Annual Income we see that people have average income and an average spending score, these people again will not be the prime targets of the shops or mall, but again they will be considered and other data analysis techniques may be used to increase their spending score.

Cluster Blue - Spenders :

This type of customers earns less but spends more Annual Income is less but spending high, so can also be treated as potential target customer we can see that people have low income but higher spending scores, these are those people who for some reason love to buy products more often even though they have a low income. Maybe it’s because these people are more than satisfied with the mall services. The shops/malls might not target these people that effectively but still will not lose them.


Cluster Purple - Target Customers :

Earning high and also spending high Target Customers. Annual Income High as well as Spending Score is high, so a target consumer. we see that people have high income and high spending scores, this is the ideal case for the mall or shops as these people are the prime sources of profit. These people might be the regular customers of the mall and are convinced by the mall’s facilities.
"""

